package Clases;

import java.awt.FileDialog;
import java.io.File;
import java.io.FilenameFilter;
import javax.swing.ImageIcon;

public class InterfazPrincipal extends javax.swing.JFrame {

    ControlDiccionario control;
    String archivoUsuario;//direccion del archivo seleccionado por el usuario

    public InterfazPrincipal() {
        initComponents();
        nombreArchivo.setText("Archivo seleccionado: Vacio");
        control = new ControlDiccionario(this);
        control.setMetodo(botonMetodo.isSelected());
        cambioBotonMetodo(botonMetodo.isSelected());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarArchivo = new javax.swing.JButton();
        nombreArchivo = new javax.swing.JLabel();
        analizarArchivo = new javax.swing.JButton();
        botonMetodo = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionarArchivo.setText("Seleccionar Archivo");
        seleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarArchivoActionPerformed(evt);
            }
        });

        nombreArchivo.setText("Archivo seleccionado:");

        analizarArchivo.setText("Analizar");
        analizarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarArchivoActionPerformed(evt);
            }
        });

        botonMetodo.setBorderPainted(false);
        botonMetodo.setContentAreaFilled(false);
        botonMetodo.setFocusPainted(false);
        botonMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMetodoActionPerformed(evt);
            }
        });

        jLabel1.setText("Busqueda binaria");

        jLabel2.setText("Hash");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seleccionarArchivo)
                        .addGap(18, 18, 18)
                        .addComponent(nombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(analizarArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(analizarArchivo)
                        .addComponent(jLabel1))
                    .addComponent(botonMetodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarArchivo)
                    .addComponent(nombreArchivo))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarArchivoActionPerformed
        FileDialog fd = new FileDialog(this, "Choose a file", FileDialog.LOAD);
        fd.setDirectory("C:\\");
        fd.setFile("*.txt");
        fd.setVisible(true);
        fd.setFilenameFilter(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.endsWith(".txt") || name.endsWith(".jpeg");
            }
        });
        String filename = fd.getFile();
        if (filename == null) {
            nombreArchivo.setText("Archivo seleccionado: Vacio");
        } else {
            nombreArchivo.setText("Archivo seleccionado: " + fd.getFile());
        }
        archivoUsuario = fd.getDirectory() + fd.getFile();
    }//GEN-LAST:event_seleccionarArchivoActionPerformed

    private void analizarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarArchivoActionPerformed
        control.leerArchivos(archivoUsuario,nombreArchivo.getText());
    }//GEN-LAST:event_analizarArchivoActionPerformed

    private void botonMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMetodoActionPerformed
    control.setMetodo(botonMetodo.isSelected());
    cambioBotonMetodo(botonMetodo.isSelected());
    }//GEN-LAST:event_botonMetodoActionPerformed
    private void cambioBotonMetodo(boolean metodo){
       if(metodo){
        ImageIcon boton = new ImageIcon("src\\main\\java\\botones\\toogleNormal.png");
         botonMetodo.setIcon(boton);
       }else {
           ImageIcon boton = new ImageIcon("src\\main\\java\\botones\\toogleInvertido.png");
            botonMetodo.setIcon(boton);
       }
       
       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarArchivo;
    private javax.swing.JToggleButton botonMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombreArchivo;
    private javax.swing.JButton seleccionarArchivo;
    // End of variables declaration//GEN-END:variables
}
