/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Clases;

import java.awt.Color;
import java.io.UnsupportedEncodingException;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;

/**
 *
 * @author felix_5bh1a4y
 */
public class VentanaOpciones extends javax.swing.JDialog {

    String texto;
    int eleccion;
    String palabraNoEncontrada;
    String palabraNueva;
    VentanaNuevaPalabra newWord;
    boolean siCambio;

    /**
     * Creates new form VentanaOpciones
     */
    public VentanaOpciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        eleccion = 0;
        cuadroTexto.setEditable(false);
        botonIgnorarTodo.setText("<html>" + "Ignorar todo y no volver a marcar" + "</html>");
        botonAgregarDiccionario.setText("<html>" + "Agregar al diccionario" + "</html>");
        newWord = new VentanaNuevaPalabra(parent, true);
    }

    public void enviarTexto(String texto, String palabraNoEncontrada) {
        this.texto = texto;
        this.palabraNoEncontrada = palabraNoEncontrada;
        cuadroTexto.setText(texto);
        subrayarPalabra();
        setVisible(true);

    }

    public String getTexto() {
        return texto;
    }

    public void subrayarPalabra() {
        try {
            Highlighter hilite = cuadroTexto.getHighlighter();
            Document doc = cuadroTexto.getDocument();
            System.out.println("Impresion del texto del cuadro:" + cuadroTexto.getText());
            String text = doc.getText(0, doc.getLength());
            int pos = 0;
            // Search for pattern
            while ((pos = text.indexOf(palabraNoEncontrada, pos)) >= 0) {
                // Create highlighter using private painter and apply around pattern
                hilite.addHighlight(pos, pos + palabraNoEncontrada.length(), new DefaultHighlighter.DefaultHighlightPainter(Color.yellow));
                pos += palabraNoEncontrada.length();
            }
        } catch (BadLocationException e) {
            System.out.println("No salio bien");
        }
    }

    public int getEleccion() {
        return eleccion;
    }

    public String transformarConAcentos(String palabra) {
        String palabraTransformada = "";
        byte[] englishBytes = palabra.getBytes();
        try {
            palabraTransformada = new String(englishBytes, "UTF8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        return palabraTransformada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIgnorar = new javax.swing.JButton();
        botonIgnorarTodo = new javax.swing.JButton();
        botonAgregarDiccionario = new javax.swing.JButton();
        botonTerminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cuadroTexto = new javax.swing.JTextPane();
        buscarReemplazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonIgnorar.setText("Ignorar");
        botonIgnorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgnorarActionPerformed(evt);
            }
        });

        botonIgnorarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgnorarTodoActionPerformed(evt);
            }
        });

        botonAgregarDiccionario.setText("A;adir");
        botonAgregarDiccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarDiccionarioActionPerformed(evt);
            }
        });

        botonTerminar.setText("Terminar");
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(cuadroTexto);

        buscarReemplazar.setText("Buscar y reemplazar");
        buscarReemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReemplazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonIgnorar)
                        .addGap(31, 31, 31)
                        .addComponent(botonIgnorarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(botonAgregarDiccionario)
                        .addGap(29, 29, 29)
                        .addComponent(buscarReemplazar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(botonTerminar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonAgregarDiccionario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarReemplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botonIgnorar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIgnorarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIgnorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgnorarActionPerformed
        eleccion = 0;
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_botonIgnorarActionPerformed

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        eleccion = 4;
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void botonIgnorarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgnorarTodoActionPerformed
        eleccion = 1;
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_botonIgnorarTodoActionPerformed

    private void botonAgregarDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarDiccionarioActionPerformed
        eleccion = 2;
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarDiccionarioActionPerformed

    private void buscarReemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReemplazarActionPerformed
        eleccion = 3;
        newWord.setTextoEstatico(palabraNoEncontrada);
        newWord.setVisible(true);
        palabraNueva = newWord.getNuevaPalabra();
        siCambio = newWord.getSiCambio();// TODO add your handling code here:
        if(siCambio){
            setVisible(false);
        }else{
            
            System.out.println("No se ingreo");
        }
    }//GEN-LAST:event_buscarReemplazarActionPerformed
    public boolean getSiCambio(){
        return siCambio;
    }
    public String getNuevaPalabra(){
        return palabraNueva;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaOpciones dialog = new VentanaOpciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarDiccionario;
    private javax.swing.JButton botonIgnorar;
    private javax.swing.JButton botonIgnorarTodo;
    private javax.swing.JButton botonTerminar;
    private javax.swing.JButton buscarReemplazar;
    private javax.swing.JTextPane cuadroTexto;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
